#!/bin/bash
set -e
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source $SCRIPTPATH/funcs/func_utils.sh
source $SCRIPTPATH/funcs/func_operators.sh
source $SCRIPTPATH/.env
touch $CURL_LOG_PATH
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

action=$1
dir=$2
fs_name=$0

usage () {
    printf "Usage: $fs_name [--help -h] \n"
    printf "Eg: \n"
    printf "\t $fs_name -h --help \n"
    printf "\t $fs_name validate env/dev\n"
    printf "\t $fs_name apply env/dev\n"
    printf "\t $fs_name sync env/dev\n"
}

while [ "$1" != "" ]; do
    case $1 in
        validate)
            f_validate_data $2
            ;;
        apply)
            f_apply $2
            ;;
        sync)
            f_sync $2
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done